// related to auth
export const STUDENT_LOGIN_REQUEST = 'STUDENT_LOGIN_REQUEST'
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS'
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL'

export const STUDENT_UPDATE = 'STUDENT_UPDATE'

export const STUDENT_READ_LS = 'STUDENT_READ_LS'

export const STUDENT_LOGOUT = 'STUDENT_LOGOUT'

// get marks (and delete marks)
export const STUDENT_SUBJECT_MARKS_REQUEST =
  'STUDENT_SUBJECT_MARKS_REQUEST'
export const STUDENT_SUBJECT_MARKS_SUCCESS =
  'STUDENT_SUBJECT_MARKS_SUCCESS'
export const STUDENT_SUBJECT_MARKS_FAIL = 'STUDENT_SUBJECT_MARKS_FAIL'
export const STUDENT_SUBJECT_MARKS_DELETE =
  'STUDENT_SUBJECT_MARKS_DELETE'

// get truancys (and delete marks)
export const STUDENT_SUBJECT_TRUANCYS_REQUEST =
  'STUDENT_SUBJECT_TRUANCYS_REQUEST'
export const STUDENT_SUBJECT_TRUANCYS_SUCCESS =
  'STUDENT_SUBJECT_TRUANCYS_SUCCESS'
export const STUDENT_SUBJECT_TRUANCYS_FAIL =
  'STUDENT_SUBJECT_TRUANCYS_FAIL'
export const STUDENT_SUBJECT_TRUANCYS_DELETE =
  'STUDENT_SUBJECT_TRUANCYS_DELETE'

// get average marks
export const STUDENT_AVERAGE_MARKS_REQUEST =
  'STUDENT_AVERAGE_MARKS_REQUEST'
export const STUDENT_AVERAGE_MARKS_SUCCESS =
  'STUDENT_AVERAGE_MARKS_SUCCESS'
export const STUDENT_AVERAGE_MARKS_FAIL = 'STUDENT_AVERAGE_MARKS_FAIL'

// get term marks
export const STUDENT_TERM_MARKS_REQUEST = 'STUDENT_TERM_MARKS_REQUEST'
export const STUDENT_TERM_MARKS_SUCCESS = 'STUDENT_TERM_MARKS_SUCCESS'
export const STUDENT_TERM_MARKS_FAIL = 'STUDENT_TERM_MARKS_FAIL'

export const STUDENT_FINAL_MARKS_REQUEST =
  'STUDENT_FINAL_MARKS_REQUEST'
export const STUDENT_FINAL_MARKS_SUCCESS =
  'STUDENT_FINAL_MARKS_SUCCESS'
export const STUDENT_FINAL_MARKS_FAIL = 'STUDENT_FINAL_MARKS_FAIL'

export const STUDENT_TIMETABLE_REQUEST = 'STUDENT_TIMETABLE_REQUEST'
export const STUDENT_TIMETABLE_SUCCESS = 'STUDENT_TIMETABLE_SUCCESS'
export const STUDENT_TIMETABLE_FAIL = 'STUDENT_TIMETABLE_FAIL'

export const STUDENT_TIMETABLE_TEACHERS_REQUEST =
  'STUDENT_TIMETABLE_TEACHERS_REQUEST'
export const STUDENT_TIMETABLE_TEACHERS_SUCCESS =
  'STUDENT_TIMETABLE_TEACHERS_SUCCESS'
export const STUDENT_TIMETABLE_TEACHERS_FAIL =
  'STUDENT_TIMETABLE_TEACHERS_FAIL'

export const STUDENT_SCHOOL_REQUEST = 'STUDENT_SCHOOL_REQUEST'
export const STUDENT_SCHOOL_SUCCESS = 'STUDENT_SCHOOL_SUCCESS'
export const STUDENT_SCHOOL_FAIL = 'STUDENT_SCHOOL_FAIL'
